spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user-managment-db
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db-changelog.yaml
    database-change-log-lock-table: DATABASECHANGELOGLOCK
    database-change-log-table: DATABASECHANGELOG

server:
  servlet:
    context-path: /user-managment-ms
  port: 8080

jwt:
  access-token:
    secret: "a-very-long-256-bit-secret-key-which-is-at-least-32-bytes-long"
    expiration-minutes: 15
  refresh-token:
    expiration-days: 30

